[book]
authors = ["Marcos Brito"]
language = "en"
multilingual = false
src = "src"
title = "Theris Documentation"

[output.html]
git-repository-url = "https://github.com/marcos-brito/theris"
site-url = "/theris/"
