[book]
authors = ["Marcos Brito"]
language = "en"
multilingual = false
src = "src"
title = "Theris Documentation"

[output.html]
git-repository-url = "https://marcos-brito.github.io/theris/"
site-url = "/theris/"
